version: '3.6'
services:
    tests:
        container_name: test
        build:
            context: .
            dockerfile: Dockerfile
            target: test
            args:
                BUILD_NUMBER: 1.0.0.1
                PAT:
        volumes:
            - ./local/tests:/artifacts/tests

    migrations:
        container_name: migration
        build:
            context: .
            dockerfile: Dockerfile
            target: migration-local
            args:
                BUILD_NUMBER: 1.0.0.1
                PAT: 
        environment:
            DOTNET_ENVIRONMENT: Development
            ConnectionStrings__Default: Host=db;Port=7010;Database=time;Username=admin;Password=Password21

    api:
        container_name: api
        build:
            context: .
            dockerfile: Dockerfile
            target: api
            args:
                BUILD_NUMBER: 1.0.0.1
                PAT:
        depends_on:
            -   migrations
            -   tests
        ports:
            -   8081:80
        environment:
            DOTNET_ENVIRONMENT: Development
            ConnectionStrings__Default: Host=db;Port=7010;Database=time;Username=admin;Password=Password21