version: '3.6'
services:
    tests:
        container_name: test
        build:
            context: .
            dockerfile: Dockerfile
            target: test
            args:
                BUILD_NUMBER: 0.0.0.1
                PAT: nuaa34o6tccmaj3piu7xooydafh7nwwszr472r5xvwvcdlg5bmuq
        volumes:
            - ./local/tests:/artifacts/tests
    migrations:
        container_name: migration
        build:
            context: .
            dockerfile: Dockerfile
            target: migration
            args:
                BUILD_NUMBER: 0.0.0.1
                PAT: nuaa34o6tccmaj3piu7xooydafh7nwwszr472r5xvwvcdlg5bmuq
        depends_on:
            -   tests
    api:
        container_name: api
        build:
            context: .
            dockerfile: Dockerfile
            target: api
            args:
                BUILD_NUMBER: 0.0.0.1
                PAT: nuaa34o6tccmaj3piu7xooydafh7nwwszr472r5xvwvcdlg5bmuq
        depends_on:
            -   migrations
            -   tests
        ports:
            -   8081:80
        environment:
            DOTNET_ENVIRONMENT: Development