services:
  db:
    image: postgres:13.3-alpine3.14
    platform: linux
    restart: unless-stopped
    environment:
      POSTGRES_DB: time
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Password21
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ./local/database/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4:5.6
    platform: linux
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: gavan@expensely.co
      PGADMIN_DEFAULT_PASSWORD: Password21
      PGADMIN_LISTEN_PORT: 80
    depends_on:
      - db
    volumes:
      - ./local/pgadmin/data:/var/lib/pgadmin
    ports:
      - "58080:80"
