name: 1.0.0$(Rev:.r)
resources:
  repositories:
    - repository: templates
      type: github
      name: gavanlamb/azure-devops-templates
      endpoint: expensely
    - repository: expensely-templates
      type: github
      name: expensely/azure-devops-templates
      endpoint: expensely

trigger: 
  - main

jobs:
  - job: build
    variables:
      - template: variables/production.ap-southeast-2.yml@expensely-templates
    displayName: Build
    steps:
      - template: ./docker/build.yml@templates
        parameters:
          target: base
          argument: "--build-arg BUILD_NUMBER=$(Build.BuildNumber) --build-arg PAT=$(System.AccessToken)"
    
      - template: ./docker/build.yml@templates
        parameters:
          target: test
          argument: "--build-arg BUILD_NUMBER=$(Build.BuildNumber) --build-arg PAT=$(System.AccessToken)"
      - template: ./docker/test.yml@templates
        parameters:
          containerName: test
    
      - template: ./docker/build.yml@templates
        parameters:
          target: api
          argument: "--build-arg BUILD_NUMBER=$(Build.BuildNumber) --build-arg PAT=$(System.AccessToken)"
      - template: ./aws/cli/ecr.push.yml@templates
        parameters:
          serviceConnectionName: ${{variables.awsServiceConnectionName}}
          region: $(region)
          imageName: api
          repositoryName: time-api
    
      - template: ./docker/build.yml@templates
        parameters:
          target: migration
          argument: "--build-arg BUILD_NUMBER=$(Build.BuildNumber) --build-arg PAT=$(System.AccessToken)"
      - template: ./aws/cli/ecr.push.yml@templates
        parameters:
          serviceConnectionName: ${{variables.awsServiceConnectionName}}
          region: $(region)
          imageName: migration
          repositoryName: time-migration

