name: 1.0$(Rev:.r)
resources:
  repositories:
    - repository: templates
      type: github
      name: gavanlamb/azure-devops-templates
      endpoint: expensely

trigger: 
  - main

jobs:
  - job: build
    displayName: Build
    steps:
      - template: ./docker/build.yml@templates
        parameters:
          target: base
          argument: "--build-arg BUILD_NUMBER=$(Build.BuildNumber) --build-arg PAT=$(System.AccessToken)"
    
      - template: ./docker/build.yml@templates
        parameters:
          target: test
      - template: ./docker/test.yml@templates
        parameters:
          containerName: test
    
      - template: ./docker/build.yml@templates
        parameters:
          target: api
      - template: ./aws/cli/ecr.push.yml@templates
        parameters:
          awsCredentials: 'AWS ap-southeast-2 production'
          awsRegion: ap-southeast-2
          imageName: api
          repositoryName: time-api
    
      - template: ./docker/build.yml@templates
        parameters:
          target: migration
      - template: ./aws/cli/ecr.push.yml@templates
        parameters:
          awsCredentials: 'AWS ap-southeast-2 production'
          awsRegion: ap-southeast-2
          imageName: migration
          repositoryName: time-migration
