name: 1.0$(Rev:.r)
resources:
  repositories:
    - repository: templates
      type: github
      name: gavanlamb/azure-devops-templates
      endpoint: expensely
    - repository: expensely-templates
      type: github
      name: expensely/azure-devops-templates
      endpoint: expensely
  pipelines:
    - pipeline: build
      source: 'Services\Time\Build'
      trigger:
        branches:
          include:
            - refs/remotes/pull*
            - refs/pull*

pool:
  vmImage: ubuntu-latest

trigger: none
pr: none

variables:
  - name: terraformVersion
    value: 1.0.2
    readonly: true

stages:
  - stage: preview
    displayName: Preview
    pool:
      vmImage: 'windows-latest'
    variables:
      - template: variables/production.ap-southeast-2.yml@expensely-templates
      - name: artifactName
        value: preview_ap-southeast-2
        readonly: true
      - name: environment
        value: preview
        readonly: true
    jobs:
      - job: setup
        displayName: Setup
        steps:
          - task: PowerShell@2
            inputs:
              targetType: inline
              script: |
                write-host("$(resources.pipeline.build.sourceBranch)")
                $branchName = "$(resources.pipeline.build.sourceBranch)"
                $nameElements = $branchName.Split("/")
                $pullRequestId = $nameElements[2]
                write-host("##vso[task.setvariable variable=pullRequestId;isOutput=true]$pullRequestId")
            name: set_variables
            displayName: Set variables
          - template: templates/environment.create.yml
            parameters:
              environmentName: Preview$(pullRequestId)
              serviceConnectionName: ${{variables.awsServiceConnectionName}}
              region: $(region)

      - job: plan
        displayName: Plan
        dependsOn: 
          - setup
        variables:
          pullRequestId: $[dependencies.setup.outputs['set_variables.pullRequestId']]
        steps:
          - template: aws/terraform/plan.yml@templates
            parameters:
              artifactName: $(artifactName)
              planAdditionalCommandOptions: '-var-file=variables/$(environment).$(region).tfvars -var="build_identifier=$(resources.pipeline.build.runName)" -var="environment=Preview$(pullRequestId)" -var="subdomain=time$(pullRequestId)"'
              serviceConnectionName: ${{variables.terraformServiceConnectionName}}
              stateBucketName: $(terraformStateBucketName)
              stateLockTableName: $(terraformStateLockTableName)
              workspaceName: service-time-$(environment)$(pullRequestId)

      - deployment: apply
        displayName: Apply
        dependsOn: 
          - plan
          - setup
        environment: preview
        variables:
          pullRequestId: $[dependencies.setup.outputs['set_variables.pullRequestId']]
        strategy:
          runOnce:
            deploy:
              steps:
                - download: none
                - template: aws/terraform/apply.yml@templates
                  parameters:
                    artifactName: $(artifactName)
                    serviceConnectionName: ${{variables.terraformServiceConnectionName}}
                - template: aws/cli/codedeploy.deploy.yml@templates
                  parameters:
                    serviceConnectionName: ${{variables.awsServiceConnectionName}}
                    region: $(region)
                    sourcePath: time-$(resources.pipeline.build.runName).yaml
                    destinationPath: time/$(environment)$(pullRequestId)/time-$(resources.pipeline.build.runName).yaml
                    codeDeployBucketName: $(codeDeployBucketName)
