name: 1.0$(Rev:.r)
resources:
  repositories:
    - repository: templates
      type: github
      name: gavanlamb/azure-devops-templates
      endpoint: expensely
  pipelines:
    - pipeline: build
      source: 'Services\Time\Build'
      trigger:
        branches:
          include:
            - refs/pull/*
          exclude:
            - '*' 

pool:
  vmImage: ubuntu-latest

trigger: none
pr: none

variables:
  - name: terraformVersion
    value: 1.0.2
    readonly: true

stages:
  - stage: preview
    displayName: Preview
    variables:
      - group: terraform_ap-southeast-2_production
      - name: artifactName
        value: preview_ap-southeast-2
        readonly: true
      - name: environment
        value: preview
        readonly: true
    jobs:
      - job: setup
        displayName: Setup
        steps:
          - script: |
              echo $(resources.pipeline.build.pipelineID)
              echo $(resources.pipeline.build.runName)
              echo $(resources.pipeline.build.runID)
              echo $(resources.pipeline.build.runURI)
              echo $(resources.pipeline.build.sourceBranch)
              echo $(resources.pipeline.build.sourceCommit)
              echo $(resources.pipeline.build.sourceProvider)
              echo $(resources.pipeline.build.requestedFor)
              echo $(resources.pipeline.build.requestedForID)


      - job: plan
        displayName: Plan
        dependsOn: setup
        steps:
          - template: aws/terraform/plan.yml@templates
            parameters:
              artifactName: $(artifactName)
              initAdditionalCommandOptions: '-no-color'
              planAdditionalCommandOptions: '-var-file=variables/$(environment).$(terraformRegion).tfvars'
              serviceConnectionName: $(terraformServiceConnectionName)
              stateBucketName: $(terraformStateBucketName)
              stateLockTableName: $(terraformStateLockTableName)
              workspaceName: service-time-$(environment)

      - deployment: apply
        displayName: Apply
        dependsOn: plan
        environment:  preview
        strategy:
          runOnce:
            deploy:
              steps:
                - download: none
                - template: aws/terraform/apply.yml@templates
                  parameters:
                    applyAdditionalCommandOptions: '-no-color'
                    artifactName: $(artifactName)
                    serviceConnectionName: $(terraformServiceConnectionName)
                # - template: templates/aws.codedeploy.yml
