name: 1.0$(Rev:.r)
resources:
  repositories:
    - repository: templates
      type: github
      name: gavanlamb/azure-devops-templates
      endpoint: expensely

pool:
  vmImage: ubuntu-latest

trigger: none

variables:
  - name: terraformVersion
    value: 1.0.2
    readonly: true

stages:
  - stage: build
    displayName: Build
    jobs:
      - job: application
        displayName: Application
        steps:
          - template: ./templates/build.yml

  - stage: preview
    displayName: Preview
    dependsOn: build
    variables:
      - group: terraform_ap-southeast-2_production
      - name: environment
        value: preview
        readonly: true
      - name: region
        value: ap-southeast-2
        readonly: true
    jobs:
      - job: setup
        displayName: Setup
        steps:
          - 

      - job: plan
        displayName: Plan
        dependsOn: setup
        steps:
          - template: aws/terraform/plan.yml@templates
            parameters:
              artifactName: $(environment)_$(TerraformRegion)
              initAdditionalCommandOptions: '-no-color'
              planAdditionalCommandOptions: '-var-file=variables/$(environment).$(region).tfvars'
              serviceConnectionName: $(terraformServiceConnectionName)
              stateBucketName: $(terraformStateBucketName)
              stateLockTableName: $(terraformStateLockTableName)
              version: $(terraformVersion)
              workspaceName: service-time-$(environment)

      - deployment: apply
        displayName: Apply
        dependsOn: plan
        environment:  preview
        strategy:
          runOnce:
            deploy:
              steps:
                - download: none
                - template: aws/terraform/apply.yml@templates
                  parameters:
                    applyAdditionalCommandOptions: '-no-color'
                    artifactName: $(environment)_$(TerraformRegion)
                    serviceConnectionName: $(terraformServiceConnectionName)
                    version: $(terraformVersion)
                - template: templates/aws.codedeploy.yml
