name: 1.0$(Rev:.r)
resources:
  repositories:
    - repository: templates
      type: github
      name: gavanlamb/azure-devops-templates
      endpoint: expensely
  pipelines:
    - pipeline: build
      source: 'Services\Time\Build'
      trigger:
        branches:
          include:
            - refs/pull/*

pool:
  vmImage: ubuntu-latest

trigger: none
pr: none

variables:
  - name: terraformVersion
    value: 1.0.2
    readonly: true

stages:
  - stage: preview
    displayName: Preview
    variables:
      - group: terraform-ap-southeast-2-production
      - name: artifactName
        value: preview_ap-southeast-2
        readonly: true
      - name: environment
        value: preview
        readonly: true
    jobs:
      - job: setup
        displayName: Setup
        steps:
          - script: |
              echo $(resources.pipeline.build.runName)

      - job: plan
        displayName: Plan
        dependsOn: setup
        steps:
          - template: aws/terraform/plan.yml@templates
            parameters:
              artifactName: $(artifactName)
              planAdditionalCommandOptions: '-var-file=variables/$(environment).$(terraformRegion).tfvars'
              serviceConnectionName: $(terraformServiceConnectionName)
              stateBucketName: $(terraformStateBucketName)
              stateLockTableName: $(terraformStateLockTableName)
              workspaceName: service-time-$(environment)$(System.PullRequest.PullRequestId)

      - deployment: apply
        displayName: Apply
        dependsOn: plan
        environment:  preview
        strategy:
          runOnce:
            deploy:
              steps:
                - download: none
                - template: aws/terraform/apply.yml@templates
                  parameters:
                    artifactName: $(artifactName)
                    serviceConnectionName: $(terraformServiceConnectionName)
                - template: aws/cli/codedeploy.yml@templates
