name: 1.0$(Rev:.r)
resources:
  repositories:
    - repository: templates
      type: github
      name: gavanlamb/azure-devops-templates
      endpoint: expensely
  pipelines:
    - pipeline: build
      source: 'Services\Time\Build'
      trigger:
        branches:
          include:
            - refs/remotes/pull*
            - refs/pull*

pool:
  vmImage: ubuntu-latest

trigger: none
pr: none

variables:
  - name: terraformVersion
    value: 1.0.2
    readonly: true

stages:
  - stage: preview
    displayName: Preview
    variables:
      - group: terraform-ap-southeast-2-production
      - name: artifactName
        value: preview_ap-southeast-2
        readonly: true
      - name: environment
        value: preview
        readonly: true
    jobs:
      - job: plan
        displayName: Plan
        dependsOn: setup
        steps:
          - powershell: |
              echo $(resources.pipeline.build.runName)
              echo '##vso[task.setvariable variable=one]secondValue'
          - task: PowerShell@2
            inputs:
              targetType: inline
              script: |
                $branchName = $(Build.SourceBranchName)
                $nameElements = $branchName.Split("/")
                $pullRequestId = $nameElements[2]
                write-host("##vso[task.setvariable variable=pullRequestId;isOutput=true]$pullRequestId")
            name: set_variables
            displayName: Set variables
          - template: aws/terraform/plan.yml@templates
            parameters:
              artifactName: $(artifactName)
              planAdditionalCommandOptions: '-var-file=variables/$(environment).$(terraformRegion).tfvars -var="build_identifier=$(resources.pipeline.build.runName)"'
              serviceConnectionName: $(terraformServiceConnectionName)
              stateBucketName: $(terraformStateBucketName)
              stateLockTableName: $(terraformStateLockTableName)
              workspaceName: service-time-$(environment)$(set_variables.pullRequestId)

      - deployment: apply
        displayName: Apply
        dependsOn: plan
        environment:  preview
        strategy:
          runOnce:
            deploy:
              steps:
                - download: none
                - template: aws/terraform/apply.yml@templates
                  parameters:
                    artifactName: $(artifactName)
                    serviceConnectionName: $(terraformServiceConnectionName)
                #- template: aws/cli/codedeploy.yml@templates
