name: 1.0$(Rev:.r)
resources:
  repositories:
    - repository: templates
      type: github
      name: gavanlamb/azure-devops-templates
      endpoint: expensely
    - repository: expensely-templates
      type: github
      name: expensely/azure-devops-templates
      endpoint: expensely

pool:
  vmImage: ubuntu-latest

trigger: none

pr:
  branches:
    include:
      - 'main'

variables:
  - template: variables/preview.ap-southeast-2.yml@expensely-templates

stages:
  - stage: build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    jobs:
      - job: build
        displayName: Build
        steps:
          - template: aws/terraform/plan.yml@templates
            parameters:
              serviceConnectionName: ${{ variables.awsServiceConnectionName }}
              region: ${{ variables.region }}

  - stage: preview
    displayName: Preview
    dependsOn:
      - build
    pool:
      vmImage: 'windows-latest'
    variables:
      - name: artifactName
        value: preview_ap-southeast-2
        readonly: true
    jobs:
      - job: setup
        displayName: Setup
        steps:
          - checkout: none
          - template: templates/environment.create.yml
            parameters:
              environmentName: Preview$(System.PullRequest.PullRequestNumber)
              serviceConnectionName: ${{ variables.awsServiceConnectionName }}
              region: ${{ variables.region }}

      - job: plan
        displayName: Plan
        dependsOn:
          - setup
        steps:
          - template: aws/terraform/plan.yml@templates
            parameters:
              artifactName: ${{ variables.artifactName }}
              planAdditionalCommandOptions: '-var-file=variables/${{ variables.environment }}.${{ variables.region }}.tfvars -var="build_identifier=$(Build.BuildNumber)" -var="environment=Preview$(System.PullRequest.PullRequestNumber)" -var="subdomain=time$(System.PullRequest.PullRequestNumber)"'
              serviceConnectionName: ${{ variables.terraformServiceConnectionName }}
              stateBucketName: ${{ variables.terraformStateBucketName }}
              stateLockTableName: ${{ variables.terraformStateLockTableName }}
              region: ${{ variables.region }}
              workspaceName: service-time-${{ variables.environment }}$(System.PullRequest.PullRequestNumber)

      - deployment: deploy
        displayName: Deploy
        dependsOn:
          - plan
          - setup
        environment: preview
        strategy:
          runOnce:
            deploy:
              steps:
                - download: none
                - template: aws/terraform/apply.yml@templates
                  parameters:
                    artifactName: ${{ variables.artifactName }}
                    serviceConnectionName: ${{variables.terraformServiceConnectionName}}
                - template: aws/cli/codedeploy.deploy.yml@templates
                  parameters:
                    serviceConnectionName: ${{variables.awsServiceConnectionName}}
                    region: ${{ variables.region }}
                    sourcePath: time-$(Build.BuildNumber).yaml
                    destinationPath: time/${{ variables.environment }}$(System.PullRequest.PullRequestNumber)/time-$(Build.BuildNumber).yaml
                    codeDeployBucketName: ${{ variables.codeDeployBucketName }}

