resources:
  repositories:
    - repository: templates
      type: github
      name: expensely/azure-devops-templates
      endpoint: expensely

pool:
  vmImage: ubuntu-latest

trigger:
  batch: true
  branches:
    include:
      - "main"

pr: none

stages:
  - stage: build
    displayName: Build
    variables:
      - template: variables/production.ap-southeast-2.yml@templates
    jobs:
      - job: setup
        displayName: Setup
        steps:
          - checkout: none
          - task: PowerShell@2
            displayName: Set build identifier
            inputs:
              targetType: inline
              script: Write-Host "##vso[build.updatebuildnumber]1.0.$(build.buildid).$(System.StageAttempt)"
              errorActionPreference: default
              showWarnings: true
              pwsh: true
      - job: api
        displayName: API
        dependsOn:
          - setup
        steps:
          - template: templates/build.api.yml
          - template: aws/iam/configure.yml@templates
          - template: templates/push.api.yml

  - stage: production
    displayName: Production
    variables:
      - template: variables/production.ap-southeast-2.yml@templates
    jobs:
      - job: plan
        displayName: Plan
        steps:
          - template: aws/iam/configure.yml@templates
          - template: terraform/plan.yml@templates
            parameters:
              artifactName: ${{ variables.TF_ARTIFACT_NAME }}
              workspaceName: service-time-${{ variables.ENVIRONMENT }}
              version: 1.1.4
              planAdditionalCommandOptions: '-var-file="variables/${{ variables.ENVIRONMENT }}.${{ variables.REGION }}.tfvars" -var="build_identifier=$(Build.BuildNumber)"'

      - template: azure-devops/approve.yml@templates
        parameters:
          dependsOn: plan
          timeoutInMinutes: 60
          userToNotify: '[Expensely]\Expensely Team'

      - deployment: deploy
        displayName: Deploy
        dependsOn: approve
        environment: Production
        strategy:
          runOnce:
            deploy:
              steps:
                - download: none
                - template: aws/iam/configure.yml@templates
                - template: terraform/apply.yml@templates
                  parameters:
                    artifactName: ${{ variables.TF_ARTIFACT_NAME }}
                    version: 1.1.4
                - template: aws/codedeploy/deploy.yml@templates
                  parameters:
                    appSpecFileName: $(Build.BuildNumber).yaml
                    destinationPath: time/${{ variables.ENVIRONMENT }}
