name: 1.0$(Rev:.r)
resources:
  repositories:
    - repository: templates
      type: github
      name: gavanlamb/azure-devops-templates
      endpoint: expensely
  pipelines:
    - pipeline: build
      source: 'Services\Time\Build'
      trigger:
        branches:
          include:
            - main

pool:
  vmImage: ubuntu-latest
  
trigger: none
pr: none

stages:
  - stage: production
    displayName: Production
    pool:
      vmImage: 'windows-latest'
    variables:
      - template: variables/production.ap-southeast-2.yml@expensely-templates
      - name: artifactName
        value: production_ap-southeast-2
        readonly: true
      - name: environment
        value: production
        readonly: true
    jobs:
      - job: plan
        displayName: Plan
        steps:
          - template: aws/terraform/plan.yml@templates
            parameters:
              artifactName: $(artifactName)
              planAdditionalCommandOptions: '-var-file=variables/$(environment).$(region).tfvars -var="build_identifier=$(resources.pipeline.build.runName)"'
              serviceConnectionName: $(terraformServiceConnectionName)
              stateBucketName: $(terraformStateBucketName)
              stateLockTableName: $(terraformStateLockTableName)
              workspaceName: service-time-$(environment)
 
      - template: job/approve.yml@templates
        parameters:
          dependsOn: plan
          timeoutInMinutes: 60
          notifyUsers: '[Expensely]\Expensely Team'

      - deployment: apply
        displayName: Apply
        dependsOn: approve
        environment: Production
        strategy:
          runOnce:
            deploy:
              steps:
                - download: none
                - template: aws/terraform/apply.yml@templates
                  parameters:
                    artifactName: $(artifactName)
                    serviceConnectionName: $(terraformServiceConnectionName)
                - template: templates/aws.codedeploy.yml
                  parameters:
                    serviceConnectionName: $(awsServiceConnectionName)
                    region: $(region)
                    sourcePath: time-$(resources.pipeline.build.runName).yaml
                    destinationPath: time/$(environment)/time-$(resources.pipeline.build.runName).yaml
                    codeDeployBucketName: $(codeDeployBucketName)
