resources:
  repositories:
    - repository: templates
      type: github
      name: expensely/azure-devops-templates
      endpoint: expensely

pool:
  vmImage: ubuntu-latest

trigger:
  batch: true
  branches:
    include:
      - "main"

pr: none

stages:
  - stage: build
    displayName: Build
    variables:
      - template: variables/production.ap-southeast-2.yml@templates
    jobs:
      - job: setup
        displayName: Setup
        steps:
          - checkout: none
          - template: templates/build.numbers.yml
      - job: api
        displayName: Api
        dependsOn:
          - setup
        steps:
          - template: templates/build.api.yml
          - template: aws/iam/configure.yml@templates
          - template: templates/push.api.yml
      - job: integration_tests
        displayName: Integration tests
        dependsOn:
          - setup
        variables:
          NPM_BUILD_NUMBER: $[ dependencies.setup.outputs['setNPMBuildIdentifier.NPMBuildNumber'] ]
        steps:
          - template: templates/build.integration-tests.yml
            parameters:
              buildNumber: $(NPM_BUILD_NUMBER)
          - template: aws/iam/configure.yml@templates
          - template: templates/push.integration-tests.yml
            parameters:
              buildNumber: $(NPM_BUILD_NUMBER)

  - stage: production
    displayName: Production
    variables:
      - template: variables/production.ap-southeast-2.yml@templates
      - name: NPM_BUILD_NUMBER
        value: $[ stageDependencies.build.setup.outputs['setNPMBuildIdentifier.NPMBuildNumber'] ]
    jobs:
      - job: plan
        displayName: Plan
        steps:
          - template: aws/iam/configure.yml@templates
          - template: terraform/plan.yml@templates
            parameters:
              artifactName: ${{ variables.TF_ARTIFACT_NAME }}
              workspaceName: service-time-${{ variables.ENVIRONMENT }}
              planAdditionalCommandOptions: '-var-file="variables/${{ variables.ENVIRONMENT }}.${{ variables.REGION }}.tfvars" -var="build_identifier=$(Build.BuildNumber)" -var="npm_build_identifier=$(NPM_BUILD_NUMBER)"'

      - template: azure-devops/approve.yml@templates
        parameters:
          dependsOn: plan
          timeoutInMinutes: 60
          userToNotify: '[Expensely]\Expensely Team'

      - deployment: deploy
        displayName: Deploy
        dependsOn: approve
        environment: Production
        strategy:
          runOnce:
            deploy:
              steps:
                - download: none
                - template: aws/iam/configure.yml@templates
                - template: terraform/apply.yml@templates
                  parameters:
                    artifactName: ${{ variables.TF_ARTIFACT_NAME }}
                - template: aws/codedeploy/deploy.yml@templates
                  parameters:
                    appSpecFileName: $(Build.BuildNumber).yaml
                    destinationPath: time/${{ variables.ENVIRONMENT }}
                - template: aws/s3/publish-test-results.yml@templates
                  parameters:
                    sourcePath: time/${{ variables.ENVIRONMENT }}
                    testResultsFileName: $(NPM_BUILD_NUMBER).xml
                    testRunTitle: Integration
